[build]
builder = "nixpacks"
buildCommand = "php artisan migrate --force"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[worker]
startCommand = "php artisan queue:work --tries=3 --verbose" 