[build]
builder = "nixpacks"
buildCommand = "php artisan queue:table && php artisan migrate --force"

[deploy]
startCommand = "php artisan config:cache && php artisan route:cache"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 