[build]
builder = "nixpacks"
buildCommand = "php artisan migrate --force"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[worker.deploy]
command = "php artisan queue:work --tries=3 --verbose"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 